@_:
    just --list

get year day_num:
    ./aoc {{ year }} {{ day_num }}

test day_num part:
    go test -run TestPart{{ part }} ./day{{ day_num }}/ -v

create day_num:
    cp -r ./day_templ day{{ day_num }}
