@run day_num *args:
    uv run ./src/aoc_2023/day{{ day_num }}/main.py {{ args }}

test day_num part:
    uv run pytest ./src/aoc_2023/day{{ day_num }} -k part_{{ part }} -vv

create day_num:
    cp -r ./templ/day_templ ./src/aoc_2023/day{{ day_num }}
