@run day_num:
    uv run ./src/aoc_2023/day{{ day_num }}/main.py

test day_num:
    uv run pytest ./src/aoc_2023/day{{ day_num }} -vv

create day_num:
    cp -r ./templ/day_templ ./src/aoc_2023/day{{ day_num }}
