@_:
    just --list

get year day_num:
    ./aoc {{ year }} {{ day_num }}

@run day_num *args:
    uv run -m src.aoc_2025.day{{ day_num }}.main {{ args }}

test day_num part *args:
    uv run -m pytest src.aoc_2025.day{{ day_num }} -k part_{{ part }} -vv

create day_num:
    cp -r ./day_templ ./src/aoc_2025/day{{ day_num }}
